### ISSUE TITLE
iText 4.2.0 was never released by iText Software 

### ISSUE THREAD

**Issue by amedee** [abevoelker/pdf_ravager#4]
I see that you distribute an iText version 4.2.0, but iText Software never made a binary (jar) release of a version 4.2.0. That means you didn't get your jar from iText Software. Please link to the third party fork where you really got your fork from, or use a version that was released by iText Software, like 2.1.7. Thanks!

**Comment by abevoelker** [comment]
This is where I got it from: https://github.com/ymasory/iText-4.2.0

I'll update to say it wasn't released by iText Software and was built by a third party. Is that satisfactory?

**Comment by amedee** [comment]
I already guessed it would be that fork. Yes, please attribute it to ymasory.
I also opened an issue there to ask ymasory to deploy the artifact on Maven Central. That would save you the trouble of having to distribute it yourself. See https://github.com/ymasory/iText-4.2.0/issues/3
